server:
    port: 8081
    servlet:
        context-path: "/authenticationandauthorization"
spring:
    application: 
        name: authentication-service
    datasource:
        url: jdbc:mysql://54.237.25.133:3306/authentication_and_authorization
        username: accessing
        password: FD;.x@!G&5es?:<M
        # url: jdbc:mysql://localhost:3306/authentication_and_authorization?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
        # username: root
        # password: p1r1chon1
        hikari:
            connectionTimeout: 20000
            maxLifetime: 27800
    jpa:
        hibernate:
            ddl-auto: update

    config: 
        import: 'optional:configserver:http://localhost:8888'
    sleuth:
        sampler:
            probability: 1.0
    cloud:
        config:
            profile: 'dev'
            uri: 'http://3.235.22.176:8888'
    redis:
        url: 'redis://3.238.245.253'
        port: 6379
    zipkin:
        base-url: 'http://3.235.22.176:9411'
eureka:
    client:
        serviceUrl:
            defaultZone: 'http://3.235.22.176:8761/eureka'
# server.servlet.context-path=/auth

logging:
    level:
        org:
            springframework: ERROR


springdoc:
    api-docs:
        path: /api-docs
    swagger-ui:
        path: /swagger-ui.html


## System Configs
system-config:
    token:
        generator: 5r'YgER_D;*n$=op&8GZ&$;0g#cx|hVhg;M=h{V>)LH$$ejSV+uDS3)"lQRt/?C
    api:
        version: 1.0.0
    email:
        sender: lanthanionbusiness@gmail.com
    mailjet:
        apiKey: 54d1004f4e3555777158b4b0cf1d51a4
        secretKey: b4447686222e17b409e27ac0c31ce7ad
        


# eureka.instance.preferIpAddress=true 
# eureka.instance.hostname = authentication-service

## jdjdjdlsdjlk

