version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/retargeting-branding-affiliate-system
hooks:
  BeforeInstall:
    - location: scripts/before_install.sh
      timeout: 300
      runas: ubuntu
  AfterInstall:
    - location: scripts/after_install.sh
      timeout: 300
      runas: ubuntu
  ApplicationStop:
    - location: scripts/before_install.sh
      timeout: 300
      runas: ubuntu
