# version: '3'

# services:
#   private:
#     image: ghcr.io/ovesorg/devices-service:dev
#     container_name: graphql-devices-service
#     volumes:
#       - '.:/app'
#       - '/app/node_modules'
#     ports:
#       - 3003:3000
#     environment:
#       - CHOKIDAR_USEPOLLING=true  



version: '3'

services:

    authentication-app:
        image: ghcr.io/lishenga/retargeting-branding-authentication
        container_name: authentication-app
        volumes:
            - /data/authentication-0.0.1-SNAPSHOT
        environment:
            - eureka.client.service-url.defaultZone=http://192.248.159.103:8761/eureka/
        expose:
            - "8081"

    retargeting_branding-app:
        image: ghcr.io/lishenga/retargeting_branding
        container_name: retargeting_branding-app
        volumes:  
            - /data/retargeting_branding-0.0.1-SNAPSHOT
        environment:
            - eureka.client.service-url.defaultZone=http://192.248.159.103:8761/eureka/
        expose:
            - "8083"

    affiliate-app:
        image: ghcr.io/lishenga/retargeting-branding-affiliate
        container_name: affiliate-app
        volumes:  
            - /data/retargeting-branding-affiliate:0.0.1-SNAPSHOT
        environment:
            - eureka.client.service-url.defaultZone=http://192.248.159.103:8761/eureka/
        expose:
            - "8080"


    nginx-auth:
        build: ./nginx/authentication
        volumes:
            - /data/authentication-0.0.1-SNAPSHOT
        ports:
            - "80:80"
        depends_on:
            - authentication-app

    nginx-retarget:
        build: ./nginx/retargeting_and_branding
        volumes:
            - /data/retargeting_branding-0.0.1-SNAPSHOT
        ports:
            - "83:83"
        depends_on:
            - retargeting_branding-app

    nginx-affiliate:
        build: ./nginx/affiliate
        volumes:
            - /data/retargeting-branding-affiliate-0.0.1-SNAPSHOT
        ports:
            - "80:80"
        depends_on:
            - affiliate-app


#             sudo apt-get update
# sudo apt-get install ruby
# sudo apt-get install wget
# cd /home/ubuntu
# wget https://aws-codedeploy-eu-west-1.s3.eu-west-1.amazonaws.com/latest/install
# chmod +x ./install
# sudo ./install auto
# sudo service codedeploy-agent start