name: Retargeting and Rebranding docker image to Amazon ECR  

on:
  push:
    branches:
      - main  

env:
  AWS_DEFAULT_REGION: us-east-1
  AWS_DEFAULT_OUTPUT: json
  AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  RETARGETING_REBRANDING_CONTAINER_IMAGE: retargettingandrebranding:latest  
  AUTHENTICATION_AUTHORIZATION_CONTAINER_IMAGE: authenticationandauthorization:latest 
  AFFILIATE_SYSTEM_CONTAINER_IMAGE: affiliatesystem:latest 

jobs:
  build-and-push:
    name: Building and pushing image to AWS ECR
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Setup ECR 
        run: |
          $( aws ecr get-login --no-include-email )

      - name: Set up JDK 14 
        uses: actions/setup-java@v1  
        with:
          java-version: 14

      - name: Maven Package
        run: |
          cd retargeting_branding
          mvn -B clean package -DskipTests
          cd ..
          cd authentication
          mvn -B clean package -DskipTests
          cd ..
          cd affiliate
          mvn -B clean package -DskipTests
          cd ..

      - name: Build and tag the retargettingandrebranding-image
        id: build-retargettingandrebranding-image
        run: |
          docker build \
            -t $RETARGETING_REBRANDING_CONTAINER_IMAGE \
            -t $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$RETARGETING_REBRANDING_CONTAINER_IMAGE ./retargeting_branding
          echo "::set-output name=image::$AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$RETARGETING_REBRANDING_CONTAINER_IMAGE"

      - name: Build and tag the authenticationandauthorization-image
        id: build-authenticationandauthorization-image
        run: |
          docker build \
            -t $AUTHENTICATION_AUTHORIZATION_CONTAINER_IMAGE \
            -t $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$AUTHENTICATION_AUTHORIZATION_CONTAINER_IMAGE ./authentication
          echo "::set-output name=image::$AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$AUTHENTICATION_AUTHORIZATION_CONTAINER_IMAGE"

      - name: Build and tag the affiliatesystem-image
        id: build-affiliatesystem-image
        run: |
          docker build \
            -t $AFFILIATE_SYSTEM_CONTAINER_IMAGE \
            -t $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$AFFILIATE_SYSTEM_CONTAINER_IMAGE ./affiliate
          echo "::set-output name=image::$AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$AFFILIATE_SYSTEM_CONTAINER_IMAGE"

      - name: Push
        run: |
          cd retargeting_branding
          docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$RETARGETING_REBRANDING_CONTAINER_IMAGE
          cd ..
          cd authentication
          docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$AUTHENTICATION_AUTHORIZATION_CONTAINER_IMAGE
          cd ..
          cd affiliate
          docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$AFFILIATE_SYSTEM_CONTAINER_IMAGE

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Fill in the new retargettingandrebranding image ID in the Amazon ECS task definition
        id: retargettingandrebranding-task-def
        uses: aws-actions/amazon-ecs-render-task-definition@v1
        with:
          task-definition: ./retargeting_branding/task-definition.json
          container-name: retargettingandrebranding
          image: ${{ steps.build-retargettingandrebranding-image.outputs.image }}

      - name: Fill in the new authenticationandauthorization image ID in the Amazon ECS task definition
        id: authenticationandauthorization-task-def
        uses: aws-actions/amazon-ecs-render-task-definition@v1
        with:
          task-definition: ./authentication/task-definition.json
          container-name: authenticationAuthorization
          image: ${{ steps.build-authenticationandauthorization-image.outputs.image }}

      - name: Fill in the new affiliatesystem image ID in the Amazon ECS task definition
        id: affiliate-task-def
        uses: aws-actions/amazon-ecs-render-task-definition@v1
        with:
          task-definition: ./affiliate/task-definition.json
          container-name: affiliatesystem
          image: ${{ steps.build-affiliate-image.outputs.image }}

      - name: Deploy Amazon retargettingandrebranding ECS task definition
        uses: aws-actions/amazon-ecs-deploy-task-definition@v1
        with:
          task-definition: ${{ steps.retargettingandrebranding-task-def.outputs.task-definition }}
          service: retargettingandrebranding
          cluster: retargettingandrebranding
          # wait-for-service-stability: true
      - name: Deploy Amazon authenticationandauthorization ECS task definition
        uses: aws-actions/amazon-ecs-deploy-task-definition@v1
        with:
          task-definition: ${{ steps.authenticationandauthorization-task-def.outputs.task-definition }}
          service: authenticationAuth
          cluster: retargettingandrebranding

      - name: Deploy Amazon affiliatesystem ECS task definition
        uses: aws-actions/amazon-ecs-deploy-task-definition@v1
        with:
          task-definition: ${{ steps.affiliatesystem-task-def.outputs.task-definition }}
          service: affiliatesystem
          cluster: retargettingandrebranding
